# $NetBSD$

COLLECTD_PACKAGE=       write_prometheus

COMMENT=                Statistics collection daemon - write_prometheus plugin

.include "../../sysutils/collectd/Makefile.common"

.include "../../devel/protobuf-c/buildlink3.mk"
.include "../../www/libmicrohttpd/buildlink3.mk"
.include "../../mk/bsd.pkg.mk"
